"""
Report Template Module

Provides template configurations for different report types.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Any
from datetime import datetime, timedelta
from enum import Enum
import logging

from reportlab.lib import colors
from reportlab.lib.units import inch

logger = logging.getLogger(__name__)


@dataclass
class TemplateConfig:
    """Template configuration settings"""
    # Page settings
    page_size: str = "letter"
    margin: float = 0.75 * inch
    
    # Colors
    primary_color: colors.Color = colors.HexColor("#1a365d")
    secondary_color: colors.Color = colors.HexColor("#2c5282")
    accent_color: colors.Color = colors.HexColor("#3182ce")
    success_color: colors.Color = colors.HexColor("#38a169")
    danger_color: colors.Color = colors.HexColor("#e53e3e")
    warning_color: colors.Color = colors.HexColor("#d69e2e")
    neutral_color: colors.Color = colors.HexColor("#718096")
    background_color: colors.Color = colors.HexColor("#f7fafc")
    text_color: colors.Color = colors.HexColor("#1a202c")
    
    # Fonts
    title_font: str = "Helvetica-Bold"
    header_font: str = "Helvetica-Bold"
    body_font: str = "Helvetica"
    
    # Font sizes
    title_size: int = 24
    subtitle_size: int = 14
    section_header_size: int = 16
    subsection_header_size: int = 12
    body_size: int = 10
    table_header_size: int = 9
    table_cell_size: int = 9
    
    # Spacing
    section_spacing: float = 20
    subsection_spacing: float = 12
    table_spacing: float = 10
    
    # Content settings
    include_summary: bool = True
    include_charts: bool = True
    include_trades_table: bool = True
    include_model_metrics: bool = True
    max_trades_in_table: int = 50
    
    # Report metadata
    report_title: str = "Polymarket AI Lead-Lag Scalper"
    report_subtitle: str = "Performance Report"
    company_name: str = "AI Lead-Lag Scalper"
    company_logo_path: Optional[str] = None


class ReportTemplate(ABC):
    """
    Abstract base class for report templates.
    
    Defines the interface and common functionality for all report templates.
    """
    
    def __init__(self, config: Optional[TemplateConfig] = None):
        """
        Initialize report template.
        
        Args:
            config: Template configuration (uses defaults if None)
        """
        self.config = config or TemplateConfig()
        
    @abstractmethod
    def get_report_type(self) -> str:
        """Get the report type identifier"""
        pass
    
    @abstractmethod
    def get_date_range(self, end_date: datetime) -> tuple:
        """Calculate the date range for this report type"""
        pass
    
    @abstractmethod
    def get_sections(self) -> List[str]:
        """Get list of sections to include in this report type"""
        pass
    
    def get_config(self) -> TemplateConfig:
        """Get template configuration"""
        return self.config
    
    def customize_for_performance(
        self,
        win_rate: float,
        total_pnl: float,
        sharpe_ratio: float,
    ) -> TemplateConfig:
        """
        Customize template based on performance metrics.
        
        Adjusts colors and emphasis based on trading performance.
        
        Args:
            win_rate: Win rate percentage
            total_pnl: Total profit/loss
            sharpe_ratio: Sharpe ratio
            
        Returns:
            Modified TemplateConfig
        """
        config = TemplateConfig(
            **{k: v for k, v in vars(self.config).items()}
        )
        
        # Adjust colors based on performance
        if total_pnl > 0 and win_rate > 0.5:
            # Good performance - use success colors
            config.accent_color = self.config.success_color
        elif total_pnl < 0 or win_rate < 0.4:
            # Poor performance - use warning colors
            config.accent_color = self.config.warning_color
            if sharpe_ratio < 0:
                config.accent_color = self.config.danger_color
        
        return config
    
    def get_header_text(self) -> str:
        """Get header text for the report"""
        return f"{self.config.report_title} - {self.get_report_type().capitalize()} Report"
    
    def get_footer_text(self) -> str:
        """Get footer text for the report"""
        return f"Generated by {self.config.company_name} | {datetime.now().strftime('%Y-%m-%d %H:%M')}"
    
    def should_include_section(self, section_name: str) -> bool:
        """Check if a section should be included"""
        return section_name in self.get_sections()
    
    def get_chart_configs(self) -> List[Dict[str, Any]]:
        """Get chart configurations for this template"""
        return [
            {
                "type": "line",
                "title": "Cumulative PnL Over Time",
                "x_label": "Date",
                "y_label": "PnL ($)",
            },
            {
                "type": "pie",
                "title": "Trade Outcome Distribution",
            },
            {
                "type": "bar",
                "title": "Daily PnL",
                "x_label": "Date",
                "y_label": "PnL ($)",
            },
        ]
    
    def get_summary_metrics(self) -> List[str]:
        """Get list of metrics to display in summary"""
        return [
            "total_trades",
            "win_rate",
            "total_pnl",
            "return_percentage",
            "profit_factor",
            "sharpe_ratio",
            "max_drawdown",
            "avg_trade_duration",
        ]


class DailyReportTemplate(ReportTemplate):
    """
    Template for daily performance reports.
    
    Provides detailed intraday metrics and trade-by-trade analysis.
    """
    
    def __init__(self, config: Optional[TemplateConfig] = None):
        super().__init__(config)
        # Daily reports show more detail
        self.config.max_trades_in_table = 100
        self.config.include_trades_table = True
    
    def get_report_type(self) -> str:
        return "daily"
    
    def get_date_range(self, end_date: datetime) -> tuple:
        start_date = end_date - timedelta(days=1)
        return start_date, end_date
    
    def get_sections(self) -> List[str]:
        return [
            "header",
            "summary",
            "charts",
            "trades_table",
            "hourly_breakdown",
            "model_metrics",
            "footer",
        ]
    
    def get_chart_configs(self) -> List[Dict[str, Any]]:
        configs = super().get_chart_configs()
        # Add hourly breakdown for daily reports
        configs.append({
            "type": "bar",
            "title": "Hourly PnL Distribution",
            "x_label": "Hour",
            "y_label": "PnL ($)",
        })
        return configs
    
    def get_summary_metrics(self) -> List[str]:
        metrics = super().get_summary_metrics()
        # Add daily-specific metrics
        metrics.extend([
            "winning_trades",
            "losing_trades",
            "avg_win",
            "avg_loss",
        ])
        return metrics


class WeeklyReportTemplate(ReportTemplate):
    """
    Template for weekly performance reports.
    
    Provides week-over-week comparison and trend analysis.
    """
    
    def __init__(self, config: Optional[TemplateConfig] = None):
        super().__init__(config)
        self.config.max_trades_in_table = 50
    
    def get_report_type(self) -> str:
        return "weekly"
    
    def get_date_range(self, end_date: datetime) -> tuple:
        start_date = end_date - timedelta(weeks=1)
        return start_date, end_date
    
    def get_sections(self) -> List[str]:
        return [
            "header",
            "summary",
            "charts",
            "daily_breakdown",
            "trades_table",
            "model_metrics",
            "footer",
        ]
    
    def get_chart_configs(self) -> List[Dict[str, Any]]:
        configs = super().get_chart_configs()
        # Add weekly-specific charts
        configs.extend([
            {
                "type": "bar",
                "title": "Daily Trade Count",
                "x_label": "Day",
                "y_label": "Trades",
            },
            {
                "type": "line",
                "title": "Cumulative PnL This Week",
                "x_label": "Day",
                "y_label": "Cumulative PnL ($)",
            },
        ])
        return configs
    
    def get_summary_metrics(self) -> List[str]:
        metrics = super().get_summary_metrics()
        metrics.extend([
            "best_day",
            "worst_day",
            "avg_daily_pnl",
        ])
        return metrics


class MonthlyReportTemplate(ReportTemplate):
    """
    Template for monthly performance reports.
    
    Provides comprehensive monthly analysis with trends and comparisons.
    """
    
    def __init__(self, config: Optional[TemplateConfig] = None):
        super().__init__(config)
        # Monthly reports summarize more
        self.config.max_trades_in_table = 30
        self.config.include_trades_table = True
    
    def get_report_type(self) -> str:
        return "monthly"
    
    def get_date_range(self, end_date: datetime) -> tuple:
        start_date = end_date - timedelta(days=30)
        return start_date, end_date
    
    def get_sections(self) -> List[str]:
        return [
            "header",
            "summary",
            "charts",
            "weekly_breakdown",
            "trades_table",
            "model_metrics",
            "performance_trends",
            "footer",
        ]
    
    def get_chart_configs(self) -> List[Dict[str, Any]]:
        configs = super().get_chart_configs()
        # Add monthly-specific charts
        configs.extend([
            {
                "type": "bar",
                "title": "Weekly PnL Breakdown",
                "x_label": "Week",
                "y_label": "PnL ($)",
            },
            {
                "type": "line",
                "title": "Win Rate Trend",
                "x_label": "Week",
                "y_label": "Win Rate (%)",
            },
            {
                "type": "bar",
                "title": "Trade Distribution by Market",
                "x_label": "Market",
                "y_label": "Trades",
            },
        ])
        return configs
    
    def get_summary_metrics(self) -> List[str]:
        metrics = super().get_summary_metrics()
        metrics.extend([
            "best_week",
            "worst_week",
            "avg_weekly_pnl",
            "total_fees",
            "net_return",
        ])
        return metrics


# Template registry
TEMPLATES = {
    "daily": DailyReportTemplate,
    "weekly": WeeklyReportTemplate,
    "monthly": MonthlyReportTemplate,
}


def get_template(report_type: str, config: Optional[TemplateConfig] = None) -> ReportTemplate:
    """
    Get a report template by type.
    
    Args:
        report_type: Type of report ('daily', 'weekly', 'monthly')
        config: Optional template configuration
        
    Returns:
        ReportTemplate instance
        
    Raises:
        ValueError: If report type is not recognized
    """
    template_class = TEMPLATES.get(report_type.lower())
    if template_class is None:
        raise ValueError(
            f"Unknown report type: {report_type}. "
            f"Available types: {list(TEMPLATES.keys())}"
        )
    return template_class(config)


def list_templates() -> List[str]:
    """Get list of available template types"""
    return list(TEMPLATES.keys())
